### ISSUE TITLE
Add all attendees to the REST Fest East team

### ISSUE THREAD

**Issue by BigBlueHat** [RESTFest/2018-Greenville#1]
@oestrich could you knock this one out for me? Everyone should've (ideally) put their GitHub names into their tickets in Ti.to. I'd like to get them all added to the newly created [2018 East Attendees](https://github.com/orgs/RESTFest/teams/2018-east-attendees) team--which has write creds on this repo.

That should set things up for group wide communication via the team discussion space, etc.

Thanks in advance!
🎩

**Comment by oestrich** [comment]
I don't think I have permission for this, I don't see a button to add new members to the team.

Once I can I'll get it set up!

**Comment by BigBlueHat** [comment]
Should be fixed!

**Comment by oestrich** [comment]
All current tickets should be invited! I'll keep this up to date as well as new tickets come in.
